### ISSUE TITLE
Default deployment instructions fail in `us-east-1`

### ISSUE THREAD

**Issue by declanvk** [aws-samples/amazon-sagemaker-studio-vpc-networkfirewall#4]
## Problem

Running the default deployment instructions (detailed in the [§Deployment](https://github.com/aws-samples/amazon-sagemaker-studio-vpc-networkfirewall#deployment-steps)) will run into the following issue when deployed in `us-east-1`:

```
2022-07-18 13:20:25 UTC+0100 DataBucket CREATE_FAILED sagemaker-studio-anfw-us-east-1-data already exists
```

The cause of the issue is that the bucket name `agemaker-studio-anfw-us-east-1-data` is already taken by someone else in this region. The S3 bucket name is generated from the `PROJECT_NAME` variable (specified [in the Makefile](https://github.com/aws-samples/amazon-sagemaker-studio-vpc-networkfirewall/blob/master/Makefile#L15)). Changing that variable to something else allows the CFN stack to deploy successfully.

## Ask

I think the main issue here is that customers might get confused when seeing this error message (I was also confused at first) and not understand the uniqueness constraint on S3 buckets.

Could we add some documentation that explains this error and what to do in case they run into it? Or, could we modify the project name to include some random element so that the likelihood of bucket name collision is much lower?

**Comment by yevgeniyilyin** [comment]
fixed by added an account id to the S3 bucket name
